apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: project-dev
  
spec:
  replicas: 2

  selectors:
    matchLabels: 
      app: project
  

  template:
    metadata: 
      app: project

      
    spec:
      containers: 
        name: project
        image: jaydevopswork/project:v1
        ports:
          containerPort: 80
    
